nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: 10.0.2.9
  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: wazuh-1
      ip: 10.0.2.9
  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: 10.0.2.9